"""init table

Revision ID: f79feaf6ddcd
Revises: 3c9063ccac32
Create Date: 2021-03-10 16:48:27.436748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f79feaf6ddcd'
down_revision = '3c9063ccac32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ih_house_facility',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ih_facility_info.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['ih_house_info.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'facility_id')
    )
    op.drop_table('in_house_facility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_house_facility',
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('facility_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ih_facility_info.id'], name='in_house_facility_ibfk_1'),
    sa.ForeignKeyConstraint(['house_id'], ['ih_house_info.id'], name='in_house_facility_ibfk_2'),
    sa.PrimaryKeyConstraint('house_id', 'facility_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ih_house_facility')
    # ### end Alembic commands ###
